REM Generated by Copilot, AI slop but necessary for updating "404.html" which GitHub Pages
REM will use to serve /register
@echo off
setlocal

if not exist index.html (
    echo ❌ index.html not found!
    exit /b 1
)

copy /Y index.html 404.html >nul
if %errorlevel% equ 0 (
    echo ✅ 404.html successfully created from index.html
) else (
    echo ❌ Failed to copy index.html to 404.html
)

endlocal